Repository keymanapp/keyboards, pull requests merged in 2020-08, with the labels that each got.

#1300 [aksarabali_panlex] update documentation and Vimala font
  release/a/aksarabali_panlex/HISTORY.md
  release/a/aksarabali_panlex/LICENSE.md
  release/a/aksarabali_panlex/README.md
  release/a/aksarabali_panlex/aksarabali_panlex.kpj
  release/a/aksarabali_panlex/source/aksarabali_panlex.kmn
  release/a/aksarabali_panlex/source/aksarabali_panlex.kps
  release/a/aksarabali_panlex/source/fonts/Vimala.ttf
  release/a/aksarabali_panlex/source/help/aksarabali_panlex.php
  release/a/aksarabali_panlex/source/readme.htm
  release/a/aksarabali_panlex/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1302 [Tawallammat Latin] Update mobile layout
  release/t/tawallammat_latin/HISTORY.md
  release/t/tawallammat_latin/README.md
  release/t/tawallammat_latin/source/help/tawallammat_latin.php
  release/t/tawallammat_latin/source/help/tawallammat_latin_longpress.jpg
  release/t/tawallammat_latin/source/help/tawallammat_latin_longpress_a.jpg
  release/t/tawallammat_latin/source/tawallammat_latin.ico
  release/t/tawallammat_latin/source/tawallammat_latin.keyman-touch-layout
  release/t/tawallammat_latin/source/tawallammat_latin.kmn
  release/t/tawallammat_latin/source/tawallammat_latin.kps
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_default_touch.jpg
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_default_touch.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_longpress.jpg
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_longpress.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_longpress_a.jpg
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_num_touch.jpg
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_num_touch.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_shift_touch.jpg
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_shift_touch.png
  release/t/tawallammat_latin/source/welcome/welcome.htm
  release/t/tawallammat_latin/tawallammat_latin.kpj
Labels: enhancement, keyboard, work-in-progress

#1309 [tawallammat_latin] Update metadata
  release/t/tawallammat_latin/HISTORY.md
  release/t/tawallammat_latin/README.md
  release/t/tawallammat_latin/source/help/tawallammat_latin.php
  release/t/tawallammat_latin/source/readme.htm
  release/t/tawallammat_latin/source/tawallammat_latin.kmn
  release/t/tawallammat_latin/source/welcome/welcome.htm
  release/t/tawallammat_latin/tawallammat_latin.kpj
Labels: enhancement, keyboard, ready-to-merge
