Repository keymanapp/keyboards, pull requests merged in 2020-06, with the labels that each got.

#1240 [ekwtamil99uni] Updated to support Linux, macOS, added mobile layout,…
  release/e/ekwtamil99uni/HISTORY.md
  release/e/ekwtamil99uni/LICENSE.md
  release/e/ekwtamil99uni/README.md
  release/e/ekwtamil99uni/ekwtamil99uni.keyboard_info
  release/e/ekwtamil99uni/ekwtamil99uni.kpj
  release/e/ekwtamil99uni/source/ekwtamil99uni-wchart.htm
  release/e/ekwtamil99uni/source/ekwtamil99uni.bmp
  release/e/ekwtamil99uni/source/ekwtamil99uni.ico
  release/e/ekwtamil99uni/source/ekwtamil99uni.keyman-touch-layout
  release/e/ekwtamil99uni/source/ekwtamil99uni.kmn
  release/e/ekwtamil99uni/source/ekwtamil99uni.kps
  release/e/ekwtamil99uni/source/ekwtamil99uni.kvk
  release/e/ekwtamil99uni/source/ekwtamil99uni.kvks
  release/e/ekwtamil99uni/source/help/ekwtamil99uni.php
  release/e/ekwtamil99uni/source/readme.htm
  release/e/ekwtamil99uni/source/welcome/keyboardchart.htm
  release/e/ekwtamil99uni/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1228 [rac_torwali] Rachitrali-Torwali
  release/rac/rac_torwali/HISTORY.md
  release/rac/rac_torwali/LICENSE.md
  release/rac/rac_torwali/README.md
  release/rac/rac_torwali/rac_torwali.keyboard_info
  release/rac/rac_torwali/rac_torwali.kpj
  release/rac/rac_torwali/source/help/rac_torwali base.png
  release/rac/rac_torwali/source/help/rac_torwali shift.png
  release/rac/rac_torwali/source/help/rac_torwali.php
  release/rac/rac_torwali/source/rac_torwali.ico
  release/rac/rac_torwali/source/rac_torwali.keyman-touch-layout
  release/rac/rac_torwali/source/rac_torwali.kmn
  release/rac/rac_torwali/source/rac_torwali.kps
  release/rac/rac_torwali/source/rac_torwali.kvks
  release/rac/rac_torwali/source/readme.htm
  release/rac/rac_torwali/source/welcome/RAC.jpg
  release/rac/rac_torwali/source/welcome/rac_torwali_base.png
  release/rac/rac_torwali/source/welcome/rac_torwali_shift.png
  release/rac/rac_torwali/source/welcome/welcome.htm
Labels: keyboard, new

#1242 [htm_fix_2020] Fix htm files and bump version numbers
  release/g/ghana/HISTORY.md
  release/g/ghana/README.md
  release/g/ghana/ghana.kpj
  release/g/ghana/source/ghana.kmn
  release/g/ghana/source/ghana.kps
  release/g/ghana/source/ghana.kvk
  release/g/ghana/source/readme.htm
  release/rac/rac_hazaragi/HISTORY.md
  release/rac/rac_hazaragi/README.md
  release/rac/rac_hazaragi/rac_hazaragi.kpj
  release/rac/rac_hazaragi/source/rac_hazaragi.kmn
  release/rac/rac_hazaragi/source/rac_hazaragi.kps
  release/rac/rac_hazaragi/source/readme.htm
  release/rac/rac_hazaragi/source/welcome/welcome.htm
  release/sil/sil_euro_latin/HISTORY.md
  release/sil/sil_euro_latin/README.md
  release/sil/sil_euro_latin/sil_euro_latin.kpj
  release/sil/sil_euro_latin/source/options.htm
  release/sil/sil_euro_latin/source/readme.htm
  release/sil/sil_euro_latin/source/sil_euro_latin.kmn
  release/sil/sil_euro_latin/source/usage.htm
  release/sil/sil_euro_latin/source/welcome/welcome.htm
  release/sil/sil_ipa/HISTORY.md
  release/sil/sil_ipa/README.md
  release/sil/sil_ipa/sil_ipa.kpj
  release/sil/sil_ipa/source/options.htm
  release/sil/sil_ipa/source/readme.htm
  release/sil/sil_ipa/source/sil_ipa.kmn
  release/sil/sil_ipa/source/sil_ipa.kps
  release/sil/sil_ipa/source/welcome/welcome.htm
  release/x/xinaliq/HISTORY.md
  release/x/xinaliq/README.md
  release/x/xinaliq/source/readme.htm
  release/x/xinaliq/source/xinaliq.kmn
  release/x/xinaliq/source/xinaliq.kps
  release/x/xinaliq/xinaliq.kpj
Labels: enhancement, keyboard

#1247 [easy_chakma] update the help page
  release/e/easy_chakma/source/help/Guideline.pdf
  release/e/easy_chakma/source/help/easy_chakma.php
  release/e/easy_chakma/source/help/images/image001.jpg
  release/e/easy_chakma/source/help/images/image002.jpg
  release/e/easy_chakma/source/help/images/image002.png
  release/e/easy_chakma/source/help/images/image003.jpg
  release/e/easy_chakma/source/help/images/image003.png
  release/e/easy_chakma/source/help/images/image004.png
  release/e/easy_chakma/source/help/images/image005.png
  release/e/easy_chakma/source/help/images/image006.png
  release/e/easy_chakma/source/help/images/image009.png
Labels: enhancement, work-in-progress

#1253 [rac_htm] Fix up htm files to proper format
  release/rac/rac_aer/HISTORY.md
  release/rac/rac_aer/LICENSE.md
  release/rac/rac_aer/README.md
  release/rac/rac_aer/rac_aer.kpj
  release/rac/rac_aer/source/rac_aer.kmn
  release/rac/rac_aer/source/rac_aer.kps
  release/rac/rac_aer/source/readme.htm
  release/rac/rac_aer/source/welcome/RAC.jpg
  release/rac/rac_aer/source/welcome/welcome.htm
  release/rac/rac_brahui_latin/HISTORY.md
  release/rac/rac_brahui_latin/LICENSE.md
  release/rac/rac_brahui_latin/README.md
  release/rac/rac_brahui_latin/rac_brahui_latin.kpj
  release/rac/rac_brahui_latin/source/help/rac_brahui_latin.php
  release/rac/rac_brahui_latin/source/rac_brahui_latin.kmn
  release/rac/rac_brahui_latin/source/rac_brahui_latin.kps
  release/rac/rac_brahui_latin/source/readme.htm
  release/rac/rac_brahui_latin/source/welcome/welcome.htm
  release/rac/rac_dogri/HISTORY.md
  release/rac/rac_dogri/LICENSE.md
  release/rac/rac_dogri/README.md
  release/rac/rac_dogri/rac_dogri.kpj
  release/rac/rac_dogri/source/help/rac_dogri.php
  release/rac/rac_dogri/source/rac_dogri.kmn
  release/rac/rac_dogri/source/rac_dogri.kps
  release/rac/rac_dogri/source/readme.htm
  release/rac/rac_dogri/source/welcome/welcome.htm
  release/rac/rac_gawar_bati/HISTORY.md
  release/rac/rac_gawar_bati/LICENSE.md
  release/rac/rac_gawar_bati/README.md
  release/rac/rac_gawar_bati/rac_gawar_bati.kpj
  release/rac/rac_gawar_bati/source/rac_gawar_bati.kmn
  release/rac/rac_gawar_bati/source/rac_gawar_bati.kps
  release/rac/rac_gawar_bati/source/readme.htm
  release/rac/rac_gawar_bati/source/welcome/welcome.htm
  release/rac/rac_kalasha/HISTORY.md
  release/rac/rac_kalasha/LICENSE.md
  release/rac/rac_kalasha/README.md
  release/rac/rac_kalasha/rac_kalasha.kpj
  release/rac/rac_kalasha/source/help/rac_kalasha.php
  release/rac/rac_kalasha/source/rac_kalasha.keyman-touch-layout
  release/rac/rac_kalasha/source/rac_kalasha.kmn
  release/rac/rac_kalasha/source/rac_kalasha.kps
  release/rac/rac_kalasha/source/readme.htm
  release/rac/rac_kalasha/source/welcome/welcome.htm
  release/rac/rac_urdu/HISTORY.md
  release/rac/rac_urdu/LICENSE.md
  release/rac/rac_urdu/README.md
  release/rac/rac_urdu/rac_urdu.kpj
  release/rac/rac_urdu/source/rac_urdu.kmn
  release/rac/rac_urdu/source/rac_urdu.kps
  release/rac/rac_urdu/source/readme.htm
  release/rac/rac_urdu/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1252 [gff_htm] Fix htm headers for GFF keyboards
  release/gff/gff_amharic/HISTORY.md
  release/gff/gff_amharic/README.md
  release/gff/gff_amharic/gff_amharic.keyboard_info
  release/gff/gff_amharic/gff_amharic.kpj
  release/gff/gff_amharic/source/gff_amharic.kmn
  release/gff/gff_amharic/source/gff_amharic.kps
  release/gff/gff_amharic/source/welcome.htm
  release/gff/gff_blin/HISTORY.md
  release/gff/gff_blin/README.md
  release/gff/gff_blin/gff_blin.kpj
  release/gff/gff_blin/source/gff_blin.kmn
  release/gff/gff_blin/source/gff_blin.kps
  release/gff/gff_blin/source/welcome.htm
  release/gff/gff_geez/HISTORY.md
  release/gff/gff_geez/README.md
  release/gff/gff_geez/gff_geez.kpj
  release/gff/gff_geez/source/gff_geez.kmn
  release/gff/gff_geez/source/gff_geez.kps
  release/gff/gff_geez/source/help/gff_geez.php
  release/gff/gff_geez/source/welcome.htm
  release/gff/gff_gurage/HISTORY.md
  release/gff/gff_gurage/LICENSE.md
  release/gff/gff_gurage/README.md
  release/gff/gff_gurage/gff_gurage.keyboard_info
  release/gff/gff_gurage/gff_gurage.kpj
  release/gff/gff_gurage/source/GurageTyping-Gurage.docx
  release/gff/gff_gurage/source/GurageTyping-Gurage.pdf
  release/gff/gff_gurage/source/gff_gurage.kmn
  release/gff/gff_gurage/source/gff_gurage.kps
  release/gff/gff_gurage/source/help/gff_gurage.php
  release/gff/gff_gurage/source/welcome.htm
  release/gff/gff_tigrinya_eritrea/HISTORY.md
  release/gff/gff_tigrinya_eritrea/README.md
  release/gff/gff_tigrinya_eritrea/gff_tigrinya_eritrea.kpj
  release/gff/gff_tigrinya_eritrea/source/gff_tigrinya_eritrea.kmn
  release/gff/gff_tigrinya_eritrea/source/gff_tigrinya_eritrea.kps
  release/gff/gff_tigrinya_eritrea/source/welcome.htm
  release/gff/gff_tigrinya_ethiopia/HISTORY.md
  release/gff/gff_tigrinya_ethiopia/README.md
  release/gff/gff_tigrinya_ethiopia/gff_tigrinya_ethiopia.kpj
  release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kmn
  release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kps
  release/gff/gff_tigrinya_ethiopia/source/welcome.htm
  release/packages/gff_gurage_and_amharic/HISTORY.md
  release/packages/gff_gurage_and_amharic/README.md
  release/packages/gff_gurage_and_amharic/gff_gurage_and_amharic.kpj
  release/packages/gff_gurage_and_amharic/source/gff_amharic_welcome.htm
  release/packages/gff_gurage_and_amharic/source/gff_gurage_and_amharic.kps
  release/packages/gff_gurage_and_amharic/source/gff_gurage_welcome.htm
  release/packages/gff_gurage_and_amharic/source/readme.htm
  release/packages/gff_gurage_and_amharic/source/welcome.htm
  release/shared/gff/readme.htm
Labels: enhancement, keyboard

#1255 [greekclassical] Move keyboard to release
  legacy/g/greekclassical/greekclassical.keyboard_info
  legacy/g/greekclassical/source/greekclassical.js
  legacy/g/greekclassical/source/greekclassical.kmp
  legacy/g/greekclassical/source/help/greekclassical-chart2.php
  release/g/greekclassical/HISTORY.md
  release/g/greekclassical/LICENSE.md
  release/g/greekclassical/README.md
  release/g/greekclassical/greekclassical.keyboard_info
  release/g/greekclassical/greekclassical.kpj
  release/g/greekclassical/source/greekclassical.ico
  release/g/greekclassical/source/greekclassical.kmn
  release/g/greekclassical/source/greekclassical.kps
  release/g/greekclassical/source/greekclassical.kvks
  release/g/greekclassical/source/help/chart.php
  release/g/greekclassical/source/help/greekclassical.php
  release/g/greekclassical/source/help/keys2.gif
  release/g/greekclassical/source/help/tr.gif
  release/g/greekclassical/source/readme.htm
  release/g/greekclassical/source/welcome/LayoutU_.png
  release/g/greekclassical/source/welcome/LayoutU_RA.png
  release/g/greekclassical/source/welcome/LayoutU_S.png
  release/g/greekclassical/source/welcome/LayoutU_SRA.png
  release/g/greekclassical/source/welcome/keyboardchart.htm
  release/g/greekclassical/source/welcome/keyrenderer.js
  release/g/greekclassical/source/welcome/keys2.gif
  release/g/greekclassical/source/welcome/style.css
  release/g/greekclassical/source/welcome/tr.gif
  release/g/greekclassical/source/welcome/welcome.htm
  release/shared/fonts/sil/galatia/FONTLOG.txt
  release/shared/fonts/sil/galatia/GalSILB.ttf
  release/shared/fonts/sil/galatia/GalSILR.ttf
  release/shared/fonts/sil/galatia/OFL-FAQ.txt
  release/shared/fonts/sil/galatia/OFL.txt
Labels: keyboard, new

#1257 [sil_cam] Fix sil_cameroon keyboards for Linux use
  release/sil/sil_cameroon_azerty/HISTORY.md
  release/sil/sil_cameroon_azerty/LICENSE.md
  release/sil/sil_cameroon_azerty/README.md
  release/sil/sil_cameroon_azerty/sil_cameroon_azerty.kpj
  release/sil/sil_cameroon_azerty/source/help/sil_cameroon_azerty.php
  release/sil/sil_cameroon_azerty/source/readme.htm
  release/sil/sil_cameroon_azerty/source/sil_cameroon_azerty.kmn
  release/sil/sil_cameroon_azerty/source/sil_cameroon_azerty.kps
  release/sil/sil_cameroon_azerty/source/welcome/welcome.htm
  release/sil/sil_cameroon_qwerty/HISTORY.md
  release/sil/sil_cameroon_qwerty/LICENSE.md
  release/sil/sil_cameroon_qwerty/README.md
  release/sil/sil_cameroon_qwerty/sil_cameroon_qwerty.kpj
  release/sil/sil_cameroon_qwerty/source/help/sil_cameroon_qwerty.php
  release/sil/sil_cameroon_qwerty/source/readme.htm
  release/sil/sil_cameroon_qwerty/source/sil_cameroon_qwerty.kmn
  release/sil/sil_cameroon_qwerty/source/sil_cameroon_qwerty.kps
  release/sil/sil_cameroon_qwerty/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1259 [nrc_crk_cans] fix Y final; add rare nwV syllabics
  release/nrc/nrc_crk_cans/HISTORY.md
  release/nrc/nrc_crk_cans/nrc_crk_cans.kpj
  release/nrc/nrc_crk_cans/source/nrc_crk_cans.keyman-touch-layout
  release/nrc/nrc_crk_cans/source/nrc_crk_cans.kmn
  release/nrc/nrc_crk_cans/source/nrc_crk_cans.kps
Labels: enhancement, keyboard

#1256 [korean_php] Fix indentation in help file
  release/k/korean_rr/source/help/korean_rr.php
Labels: enhancement, keyboard

#1254 [rac_kashmiri] Rachitrali-Kashmiri Keyboard
  release/rac/rac_kashmiri/HISTORY.md
  release/rac/rac_kashmiri/LICENSE.md
  release/rac/rac_kashmiri/README.md
  release/rac/rac_kashmiri/rac_kashmiri.keyboard_info
  release/rac/rac_kashmiri/rac_kashmiri.kpj
  release/rac/rac_kashmiri/source/help/rac_kashmiri.php
  release/rac/rac_kashmiri/source/help/rac_kashmiri_base.png
  release/rac/rac_kashmiri/source/help/rac_kashmiri_shift.png
  release/rac/rac_kashmiri/source/rac_kashmiri.ico
  release/rac/rac_kashmiri/source/rac_kashmiri.keyman-touch-layout
  release/rac/rac_kashmiri/source/rac_kashmiri.kmn
  release/rac/rac_kashmiri/source/rac_kashmiri.kps
  release/rac/rac_kashmiri/source/rac_kashmiri.kvks
  release/rac/rac_kashmiri/source/readme.htm
  release/rac/rac_kashmiri/source/welcome/RAC.jpg
  release/rac/rac_kashmiri/source/welcome/rac_kashmiri_base.png
  release/rac/rac_kashmiri/source/welcome/rac_kashmiri_shift.png
  release/rac/rac_kashmiri/source/welcome/welcome.htm
Labels: keyboard, new, work-in-progress

#1262 [fv_kwakwala_liqwala] Revert mobile layout and fix headers on htm files
  release/fv/fv_kwakwala_liqwala/HISTORY.md
  release/fv/fv_kwakwala_liqwala/LICENSE.md
  release/fv/fv_kwakwala_liqwala/README.md
  release/fv/fv_kwakwala_liqwala/fv_kwakwala_liqwala.kpj
  release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.keyman-touch-layout
  release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kmn
  release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kps
  release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala_kmw_help.htm
  release/fv/fv_kwakwala_liqwala/source/welcome/welcome.htm
Labels: enhancement, keyboard
