Repository keymanapp/keyboards, pull requests merged in 2020-07, with the labels that each got.

#1258 [fv_plains_cree] Change Y final
  release/fv/fv_plains_cree/HISTORY.md
  release/fv/fv_plains_cree/LICENSE.md
  release/fv/fv_plains_cree/README.md
  release/fv/fv_plains_cree/fv_plains_cree.kpj
  release/fv/fv_plains_cree/source/fv_plains_cree.keyman-touch-layout
  release/fv/fv_plains_cree/source/fv_plains_cree.kmn
  release/fv/fv_plains_cree/source/fv_plains_cree.kps
  release/fv/fv_plains_cree/source/help/fv_plains_cree.php
Labels: enhancement, keyboard

#1279 GFF Gurage 0.7 Beta 2
  release/gff/gff_gurage/HISTORY.md
  release/gff/gff_gurage/README.md
  release/gff/gff_gurage/gff_gurage.kpj
  release/gff/gff_gurage/source/gff_gurage.keyman-touch-layout
  release/gff/gff_gurage/source/gff_gurage.kmn
  release/gff/gff_gurage/source/gff_gurage.kps
Labels: enhancement, keyboard

#1280 [easy_chakma] Update Font
  release/e/easy_chakma/HISTORY.md
  release/e/easy_chakma/README.md
  release/e/easy_chakma/easy_chakma.kpj
  release/e/easy_chakma/source/easy_chakma.kmn
  release/e/easy_chakma/source/readme.htm
  release/shared/fonts/chakma/RibengUni-Regular.ttf
Labels: enhancement

#1282 [athinkra_vai] Move Vai (Athinkra) to release with permission of Athinkra
  legacy/v/vai1.1/DEPRECATED.md
  release/athinkra/athinkra_vai/HISTORY.md
  release/athinkra/athinkra_vai/LICENSE.md
  release/athinkra/athinkra_vai/README.md
  release/athinkra/athinkra_vai/athinkra_vai.keyboard_info
  release/athinkra/athinkra_vai/athinkra_vai.kpj
  release/athinkra/athinkra_vai/source/athinkra_vai.ico
  release/athinkra/athinkra_vai/source/athinkra_vai.kmn
  release/athinkra/athinkra_vai/source/athinkra_vai.kps
  release/athinkra/athinkra_vai/source/athinkra_vai.kvks
  release/athinkra/athinkra_vai/source/help/athinkra_vai.php
  release/athinkra/athinkra_vai/source/readme.htm
  release/athinkra/athinkra_vai/source/welcome/LayoutU_.png
  release/athinkra/athinkra_vai/source/welcome/LayoutU_RA.png
  release/athinkra/athinkra_vai/source/welcome/LayoutU_S.png
  release/athinkra/athinkra_vai/source/welcome/LayoutU_SRA.png
  release/athinkra/athinkra_vai/source/welcome/welcome.htm
  release/shared/fonts/vaii/Dukor.ttf
  release/shared/fonts/vaii/DukorItalic.ttf
  release/shared/fonts/vaii/Wakor.ttf
  release/shared/fonts/vaii/WakorOblique.ttf
  release/shared/fonts/vaii/dukor-licence.txt
  release/shared/fonts/vaii/wakor-licence.txt
Labels: keyboard, new

#1283 [qom] Initial submission
  release/q/qom/HISTORY.md
  release/q/qom/LICENSE.md
  release/q/qom/README.md
  release/q/qom/qom.keyboard_info
  release/q/qom/qom.kpj
  release/q/qom/source/LA.jpg
  release/q/qom/source/help/qom.php
  release/q/qom/source/qom.ico
  release/q/qom/source/qom.keyman-touch-layout
  release/q/qom/source/qom.kmn
  release/q/qom/source/qom.kps
  release/q/qom/source/qom.kvks
  release/q/qom/source/qomU_.png
  release/q/qom/source/qomU_RA.png
  release/q/qom/source/qomU_S.png
  release/q/qom/source/readme.htm
  release/q/qom/source/welcome.htm
Labels: keyboard, new

#1290 [qom] Fix help file
  release/q/qom/source/help/qom.php
Labels: enhancement, keyboard

#1289 [gff_legacy] Put .js files into kmp wrapper
  legacy/gff/gff_awn_7/gff_awn_7.keyboard_info
  legacy/gff/gff_awn_7/gff_awn_7.kpj
  legacy/gff/gff_awn_7/source/SideImage.bmp
  legacy/gff/gff_awn_7/source/gff_awn_7.kmp
  legacy/gff/gff_awn_7/source/gff_awn_7.kps
  legacy/gff/gff_awn_7/source/readme.htm
  legacy/gff/gff_awn_7/source/welcome/AwngiTyping-English.pdf
  legacy/gff/gff_awn_7/source/welcome/welcome.htm
  legacy/gff/gff_bcq_7/gff_bcq_7.keyboard_info
  legacy/gff/gff_bcq_7/gff_bcq_7.kpj
  legacy/gff/gff_bcq_7/source/SideImage.bmp
  legacy/gff/gff_bcq_7/source/gff_bcq_7.kmp
  legacy/gff/gff_bcq_7/source/gff_bcq_7.kps
  legacy/gff/gff_bcq_7/source/readme.htm
  legacy/gff/gff_mym_7/gff_mym_7.keyboard_info
  legacy/gff/gff_mym_7/gff_mym_7.kpj
  legacy/gff/gff_mym_7/source/SideImage.bmp
  legacy/gff/gff_mym_7/source/gff_mym_7.kmp
  legacy/gff/gff_mym_7/source/gff_mym_7.kps
  legacy/gff/gff_mym_7/source/readme.htm
Labels: infrastructure, keyboard

#1292 [athinkra_vai_typewriter] New keyboard on behalf of Athinkra
  release/athinkra/athinkra_vai_typewriter/HISTORY.md
  release/athinkra/athinkra_vai_typewriter/LICENSE.md
  release/athinkra/athinkra_vai_typewriter/README.md
  release/athinkra/athinkra_vai_typewriter/athinkra_vai_typewriter.keyboard_info
  release/athinkra/athinkra_vai_typewriter/athinkra_vai_typewriter.kpj
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.ico
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.kmn
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.kps
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.kvks
  release/athinkra/athinkra_vai_typewriter/source/help/athinkra_vai_typewriter.php
  release/athinkra/athinkra_vai_typewriter/source/readme.htm
  release/athinkra/athinkra_vai_typewriter/source/welcome/LayoutU_.png
  release/athinkra/athinkra_vai_typewriter/source/welcome/LayoutU_RA.png
  release/athinkra/athinkra_vai_typewriter/source/welcome/LayoutU_S.png
  release/athinkra/athinkra_vai_typewriter/source/welcome/LayoutU_SRA.png
  release/athinkra/athinkra_vai_typewriter/source/welcome/welcome.htm
Labels: keyboard, new

#1274 [tamajaq_unicode] Tamajaq-Unicode keyboard
  release/t/tawallammat_latin/HISTORY.md
  release/t/tawallammat_latin/LICENSE.md
  release/t/tawallammat_latin/README.md
  release/t/tawallammat_latin/source/help/tawallammat_latin.php
  release/t/tawallammat_latin/source/readme.htm
  release/t/tawallammat_latin/source/tawallammat_latin.ico
  release/t/tawallammat_latin/source/tawallammat_latin.keyman-touch-layout
  release/t/tawallammat_latin/source/tawallammat_latin.kmn
  release/t/tawallammat_latin/source/tawallammat_latin.kps
  release/t/tawallammat_latin/source/tawallammat_latin.kvks
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_default.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_default_touch.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_longpress.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_num_touch.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_shift.png
  release/t/tawallammat_latin/source/welcome/tawallammat_latin_shift_touch.png
  release/t/tawallammat_latin/source/welcome/welcome.htm
  release/t/tawallammat_latin/tawallammat_latin.keyboard_info
  release/t/tawallammat_latin/tawallammat_latin.kpj
Labels: keyboard, new, work-in-progress

#1297 [sxava] Add help file
  release/s/sxava/source/help/sxava.php
Labels: enhancement, keyboard

#1298 [athinkra_vai_typewriter] Update version and info in kps
  release/athinkra/athinkra_vai_typewriter/HISTORY.md
  release/athinkra/athinkra_vai_typewriter/README.md
  release/athinkra/athinkra_vai_typewriter/athinkra_vai_typewriter.kpj
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.kmn
  release/athinkra/athinkra_vai_typewriter/source/athinkra_vai_typewriter.kps
Labels: enhancement, keyboard

#1299 [sil_ipa] Update documentation on Africanist upstep and downstep
  release/sil/sil_ipa/HISTORY.md
  release/sil/sil_ipa/README.md
  release/sil/sil_ipa/sil_ipa.kpj
  release/sil/sil_ipa/source/help/sil_ipa.php
  release/sil/sil_ipa/source/sil_ipa.kmn
  release/sil/sil_ipa/source/sil_ipa.kps
  release/sil/sil_ipa/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1294 [sil_nkoo] New Desktop and mobile keyboard
  release/shared/fonts/nkoo/LICENSE_OFL.txt
  release/shared/fonts/nkoo/NotoSansNKo-Regular.ttf
  release/sil/sil_nko/HISTORY.md
  release/sil/sil_nko/LICENSE.md
  release/sil/sil_nko/README.md
  release/sil/sil_nko/sil_nko.keyboard_info
  release/sil/sil_nko/sil_nko.kpj
  release/sil/sil_nko/source/help/sil_nko.php
  release/sil/sil_nko/source/readme.htm
  release/sil/sil_nko/source/sil_nko.ico
  release/sil/sil_nko/source/sil_nko.keyman-touch-layout
  release/sil/sil_nko/source/sil_nko.kmn
  release/sil/sil_nko/source/sil_nko.kps
  release/sil/sil_nko/source/sil_nko.kvks
  release/sil/sil_nko/source/welcome/LayoutU_.png
  release/sil/sil_nko/source/welcome/LayoutU_RA.png
  release/sil/sil_nko/source/welcome/LayoutU_S.png
  release/sil/sil_nko/source/welcome/welcome.htm
Labels: keyboard, new
