Repository keymanapp/keyboards, pull requests merged in 2021-07, with the labels that each got.

#1587 [nrc_makah] Add new version of Andika to keyboard
  release/nrc/nrc_makah/HISTORY.md
  release/nrc/nrc_makah/LICENSE.md
  release/nrc/nrc_makah/README.md
  release/nrc/nrc_makah/nrc_makah.kpj
  release/nrc/nrc_makah/source/nrc_makah.kmn
  release/nrc/nrc_makah/source/nrc_makah.kps
  release/nrc/nrc_makah/source/readme.htm
  release/nrc/nrc_makah/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1540 [qwerty_farang] QWERTY Farang
  release/q/qwerty_farang/HISTORY.md
  release/q/qwerty_farang/LICENSE.md
  release/q/qwerty_farang/README.md
  release/q/qwerty_farang/qwerty_farang.keyboard_info
  release/q/qwerty_farang/qwerty_farang.kpj
  release/q/qwerty_farang/source/help/ct5k.png
  release/q/qwerty_farang/source/help/qwerty_farang.php
  release/q/qwerty_farang/source/help/touch_longpress.png
  release/q/qwerty_farang/source/qwerty_farang.css
  release/q/qwerty_farang/source/qwerty_farang.ico
  release/q/qwerty_farang/source/qwerty_farang.keyman-touch-layout
  release/q/qwerty_farang/source/qwerty_farang.kmn
  release/q/qwerty_farang/source/qwerty_farang.kps
  release/q/qwerty_farang/source/qwerty_farang.kvks
  release/q/qwerty_farang/source/readme.htm
  release/q/qwerty_farang/source/welcome/ct5k.png
  release/q/qwerty_farang/source/welcome/desktop_layoutU_.png
  release/q/qwerty_farang/source/welcome/desktop_layoutU_RA.png
  release/q/qwerty_farang/source/welcome/desktop_layoutU_S.png
  release/q/qwerty_farang/source/welcome/touch_default.png
  release/q/qwerty_farang/source/welcome/touch_longpress.png
  release/q/qwerty_farang/source/welcome/touch_numeric.png
  release/q/qwerty_farang/source/welcome/welcome.htm
Labels: keyboard, new

#1596 [obolo_chwerty] v1.2.0 update
  release/o/obolo_chwerty/HISTORY.md
  release/o/obolo_chwerty/README.md
  release/o/obolo_chwerty/obolo_chwerty.keyboard_info
  release/o/obolo_chwerty/obolo_chwerty.kpj
  release/o/obolo_chwerty/source/help/chwerty_default.png
  release/o/obolo_chwerty/source/help/chwerty_keycombi.png
  release/o/obolo_chwerty/source/help/chwerty_mobi_alt.png
  release/o/obolo_chwerty/source/help/chwerty_mobi_default.png
  release/o/obolo_chwerty/source/help/chwerty_mobi_shift.png
  release/o/obolo_chwerty/source/help/chwerty_shift.png
  release/o/obolo_chwerty/source/help/obolo_chwerty.php
  release/o/obolo_chwerty/source/notosans_regular.ttf
  release/o/obolo_chwerty/source/obolo_chwerty.keyman-touch-layout
  release/o/obolo_chwerty/source/obolo_chwerty.kmn
  release/o/obolo_chwerty/source/obolo_chwerty.kps
  release/o/obolo_chwerty/source/obolo_chwerty.kvks
  release/o/obolo_chwerty/source/readme.htm
  release/o/obolo_chwerty/source/welcome/chwerty_default.png
  release/o/obolo_chwerty/source/welcome/chwerty_keycombi.png
  release/o/obolo_chwerty/source/welcome/chwerty_mobi_alt.png
  release/o/obolo_chwerty/source/welcome/chwerty_mobi_default.png
  release/o/obolo_chwerty/source/welcome/chwerty_mobi_shift.png
  release/o/obolo_chwerty/source/welcome/chwerty_shift.png
  release/o/obolo_chwerty/source/welcome/welcome.htm
Labels: enhancement

#1594 [taigi_poj] v1.3: tone marks for "un", colon & semicolon on touch keyboard
  experimental/t/taigi_poj/HISTORY.md
  experimental/t/taigi_poj/LICENSE.md
  experimental/t/taigi_poj/README.md
  experimental/t/taigi_poj/source/taigi_poj.keyman-touch-layout
  experimental/t/taigi_poj/source/taigi_poj.kmn
  experimental/t/taigi_poj/source/taigi_poj.kps
  experimental/t/taigi_poj/taigi_poj.kpj
Labels: enhancement, keyboard

#1604 fix(balochi_phonetic): typo in .kps masking .ttf
  release/b/balochi_phonetic/HISTORY.md
  release/b/balochi_phonetic/balochi_phonetic.kpj
  release/b/balochi_phonetic/source/balochi_phonetic.kmn
  release/b/balochi_phonetic/source/balochi_phonetic.kps
Labels: bug

#1601 [font-sch] Update version of font
  release/shared/fonts/sil/scheherazade_new/FONTLOG.txt
  release/shared/fonts/sil/scheherazade_new/ScheherazadeNew-Bold.ttf
  release/shared/fonts/sil/scheherazade_new/ScheherazadeNew-Regular.ttf
Labels: enhancement

#1597 [wakhi_standard] New keyboard submitted on behalf of author
  experimental/w/wakhi_standard/HISTORY.md
  experimental/w/wakhi_standard/LICENSE.md
  experimental/w/wakhi_standard/README.md
  experimental/w/wakhi_standard/source/help/wakhi_standard.php
  experimental/w/wakhi_standard/source/readme.htm
  experimental/w/wakhi_standard/source/wakhi_standard.ico
  experimental/w/wakhi_standard/source/wakhi_standard.keyman-touch-layout
  experimental/w/wakhi_standard/source/wakhi_standard.kmn
  experimental/w/wakhi_standard/source/wakhi_standard.kps
  experimental/w/wakhi_standard/source/wakhi_standard.kvks
  experimental/w/wakhi_standard/source/welcome/LayoutU_.png
  experimental/w/wakhi_standard/source/welcome/LayoutU_S.png
  experimental/w/wakhi_standard/source/welcome/welcome.htm
  experimental/w/wakhi_standard/wakhi_standard.keyboard_info
  experimental/w/wakhi_standard/wakhi_standard.kpj
Labels: keyboard, new

#1617 [nlci_gurmukhi_winscript] New keyboard
  release/nlci/nlci_gurmukhi_winscript/HISTORY.md
  release/nlci/nlci_gurmukhi_winscript/LICENSE.md
  release/nlci/nlci_gurmukhi_winscript/README.md
  release/nlci/nlci_gurmukhi_winscript/nlci_gurmukhi_winscript.keyboard_info
  release/nlci/nlci_gurmukhi_winscript/nlci_gurmukhi_winscript.kpj
  release/nlci/nlci_gurmukhi_winscript/source/help/nlci_gurmukhi_winscript.php
  release/nlci/nlci_gurmukhi_winscript/source/nlci_gurmukhi_winscript.ico
  release/nlci/nlci_gurmukhi_winscript/source/nlci_gurmukhi_winscript.kmn
  release/nlci/nlci_gurmukhi_winscript/source/nlci_gurmukhi_winscript.kps
  release/nlci/nlci_gurmukhi_winscript/source/nlci_gurmukhi_winscript.kvks
  release/nlci/nlci_gurmukhi_winscript/source/readme.htm
  release/nlci/nlci_gurmukhi_winscript/source/welcome/welcome.htm
  source/help/h.ph
Labels: keyboard, new

#1620 Naijatype php
  experimental/n/naijatype/README.md
  experimental/n/naijatype/source/help/naijatype.php
Labels: enhancement

#1618 [colchis_latin] New keyboard
  experimental/c/colchis_latin/HISTORY.md
  experimental/c/colchis_latin/LICENSE.md
  experimental/c/colchis_latin/README.md
  experimental/c/colchis_latin/colchis_latin.keyboard_info
  experimental/c/colchis_latin/colchis_latin.kpj
  experimental/c/colchis_latin/source/colchis_latin.ico
  experimental/c/colchis_latin/source/colchis_latin.keyman-touch-layout
  experimental/c/colchis_latin/source/colchis_latin.kmn
  experimental/c/colchis_latin/source/colchis_latin.kps
  experimental/c/colchis_latin/source/colchis_latin.kvks
  experimental/c/colchis_latin/source/help/colchis_latin.php
  experimental/c/colchis_latin/source/readme.htm
  experimental/c/colchis_latin/source/welcome/LayoutU_.png
  experimental/c/colchis_latin/source/welcome/LayoutU_RA.png
  experimental/c/colchis_latin/source/welcome/LayoutU_S.png
  experimental/c/colchis_latin/source/welcome/LayoutU_SRA.png
  experimental/c/colchis_latin/source/welcome/welcome.htm
Labels: keyboard, new
