Repository keymanapp/keyboards, pull requests merged in 2021-04, with the labels that each got.

#1501 [sil_nko] change OSK and touch font
  release/shared/fonts/nkoo/NotoSansNKo-Regular.ttf
  release/sil/sil_nko/HISTORY.md
  release/sil/sil_nko/LICENSE.md
  release/sil/sil_nko/README.md
  release/sil/sil_nko/sil_nko.kpj
  release/sil/sil_nko/source/readme.htm
  release/sil/sil_nko/source/sil_nko.keyman-touch-layout
  release/sil/sil_nko/source/sil_nko.kmn
  release/sil/sil_nko/source/sil_nko.kps
  release/sil/sil_nko/source/sil_nko.kvks
  release/sil/sil_nko/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1502 [khmer_angkor] fix the missing image
  release/k/khmer_angkor/HISTORY.md
  release/k/khmer_angkor/README.md
  release/k/khmer_angkor/khmer_angkor.kpj
  release/k/khmer_angkor/source/help/khmer_angkor.php
  release/k/khmer_angkor/source/khmer_angkor.kmn
  release/k/khmer_angkor/source/khmer_angkor.kps
Labels: enhancement, keyboard

#1480 [sil_eastern_congo] Updates per community request
  release/sil/sil_eastern_congo/HISTORY.md
  release/sil/sil_eastern_congo/LICENSE.md
  release/sil/sil_eastern_congo/README.md
  release/sil/sil_eastern_congo/sil_eastern_congo.kpj
  release/sil/sil_eastern_congo/source/help/sil_eastern_congo.php
  release/sil/sil_eastern_congo/source/readme.htm
  release/sil/sil_eastern_congo/source/sil_eastern_congo.keyman-touch-layout
  release/sil/sil_eastern_congo/source/sil_eastern_congo.kmn
  release/sil/sil_eastern_congo/source/sil_eastern_congo.kps
  release/sil/sil_eastern_congo/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1514 [sylheti_nagri] New keyboard on behalf of STAR
  release/s/sylheti_nagri/HISTORY.md
  release/s/sylheti_nagri/LICENSE.md
  release/s/sylheti_nagri/README.md
  release/s/sylheti_nagri/assets/FONTLOG.txt
  release/s/sylheti_nagri/assets/OFL-FAQ.txt
  release/s/sylheti_nagri/assets/OFL.txt
  release/s/sylheti_nagri/assets/README.txt
  release/s/sylheti_nagri/assets/Surma-Regular.ttf
  release/s/sylheti_nagri/source/STARcol96x96.png
  release/s/sylheti_nagri/source/help/sylheti_nagri.php
  release/s/sylheti_nagri/source/readme.htm
  release/s/sylheti_nagri/source/sylheti_nagri.ico
  release/s/sylheti_nagri/source/sylheti_nagri.keyman-touch-layout
  release/s/sylheti_nagri/source/sylheti_nagri.kmn
  release/s/sylheti_nagri/source/sylheti_nagri.kps
  release/s/sylheti_nagri/source/sylheti_nagri.kvks
  release/s/sylheti_nagri/source/welcome/LayoutU_.png
  release/s/sylheti_nagri/source/welcome/LayoutU_S.png
  release/s/sylheti_nagri/source/welcome/mobile_def.jpg
  release/s/sylheti_nagri/source/welcome/mobile_numeric.jpg
  release/s/sylheti_nagri/source/welcome/welcome.htm
  release/s/sylheti_nagri/sylheti_nagri.keyboard_info
  release/s/sylheti_nagri/sylheti_nagri.kpj
Labels: keyboard, new

#1517 [my3-help] Remove spurious end markers to help display
  release/sil/sil_myanmar_my3/HISTORY.md
  release/sil/sil_myanmar_my3/LICENSE.md
  release/sil/sil_myanmar_my3/README.md
  release/sil/sil_myanmar_my3/sil_myanmar_my3.kpj
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kmn
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kps
  release/sil/sil_myanmar_my3/source/welcome/welcome.htm
  release/sil/sil_myanmar_my3/source/welcome/welcome.html
Labels: enhancement

#1520 [sil_eastern_congo] Updated one keystroke that was problematical and …
  release/sil/sil_eastern_congo/HISTORY.md
  release/sil/sil_eastern_congo/README.md
  release/sil/sil_eastern_congo/sil_eastern_congo.kpj
  release/sil/sil_eastern_congo/source/help/sil_eastern_congo.php
  release/sil/sil_eastern_congo/source/sil_eastern_congo.kmn
  release/sil/sil_eastern_congo/source/sil_eastern_congo.kps
  release/sil/sil_eastern_congo/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1523 [sil_eastern_congo] Fix bug introduced in previous version
  release/sil/sil_eastern_congo/HISTORY.md
  release/sil/sil_eastern_congo/README.md
  release/sil/sil_eastern_congo/sil_eastern_congo.kpj
  release/sil/sil_eastern_congo/source/sil_eastern_congo.kmn
Labels: enhancement, keyboard

#1524 [sil_myanmar_my3] Change font
  release/shared/fonts/mymr/Pyidaungsu/Pyidaungsu-Bold.ttf
  release/shared/fonts/mymr/Pyidaungsu/Pyidaungsu-Numbers.ttf
  release/shared/fonts/mymr/Pyidaungsu/Pyidaungsu-Regular.ttf
  release/shared/fonts/mymr/Pyidaungsu/Pyidaungsu_Font_User_Manual_05.pdf
  release/sil/sil_myanmar_my3/HISTORY.md
  release/sil/sil_myanmar_my3/README.md
  release/sil/sil_myanmar_my3/sil_myanmar_my3.keyboard_info
  release/sil/sil_myanmar_my3/sil_myanmar_my3.kpj
  release/sil/sil_myanmar_my3/source/help/80x15.png
  release/sil/sil_myanmar_my3/source/help/sil_myanmar_my3.php
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.keyman-touch-layout
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kmn
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kps
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kvks
  release/sil/sil_myanmar_my3/source/welcome/80x15.png
  release/sil/sil_myanmar_my3/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1526 [tangsa_lakhum] Add font to keyboard_info and help file
  experimental/t/tangsa_lakhum/source/help/tangsa_lakhum.php
  experimental/t/tangsa_lakhum/tangsa_lakhum.keyboard_info
Labels: enhancement, keyboard

#1529 [font_awami] Update Awami font for packages
  release/shared/fonts/sil/awami/AwamiNastaliq-Regular.ttf
  release/shared/fonts/sil/awami/Awami_README.txt
  release/shared/fonts/sil/awami/FONTLOG.txt
  release/shared/fonts/sil/awami/OFL-FAQ.txt
  release/shared/fonts/sil/awami/OFL.txt
Labels: enhancement
