Repository keymanapp/keyboards, pull requests merged in 2021-11, with the labels that each got.

#1686 [mon_anonta] New keyboard on behalf of author
  release/m/mon_anonta/HISTORY.md
  release/m/mon_anonta/LICENSE.md
  release/m/mon_anonta/README.md
  release/m/mon_anonta/mon_anonta.keyboard_info
  release/m/mon_anonta/mon_anonta.kpj
  release/m/mon_anonta/source/help/mon_anonta.php
  release/m/mon_anonta/source/help/mon_anonta.png
  release/m/mon_anonta/source/help/mon_anonta_mobile_default.png
  release/m/mon_anonta/source/help/mon_anonta_mobile_numeric.png
  release/m/mon_anonta/source/help/mon_anonta_mobile_shift.png
  release/m/mon_anonta/source/help/mon_anonta_s.png
  release/m/mon_anonta/source/mon_anonta.ico
  release/m/mon_anonta/source/mon_anonta.keyman-touch-layout
  release/m/mon_anonta/source/mon_anonta.kmn
  release/m/mon_anonta/source/mon_anonta.kps
  release/m/mon_anonta/source/mon_anonta.kvks
  release/m/mon_anonta/source/readme.htm
  release/m/mon_anonta/source/welcome/mon_anonta.png
  release/m/mon_anonta/source/welcome/mon_anonta_mobile_default.png
  release/m/mon_anonta/source/welcome/mon_anonta_mobile_numeric.png
  release/m/mon_anonta/source/welcome/mon_anonta_mobile_shift.png
  release/m/mon_anonta/source/welcome/mon_anonta_s.png
  release/m/mon_anonta/source/welcome/welcome.htm
Labels: keyboard, new

#1687 [mon_phonetic] New keyboard on behalf of author
  release/m/mon_phonetic/HISTORY.md
  release/m/mon_phonetic/LICENSE.md
  release/m/mon_phonetic/README.md
  release/m/mon_phonetic/mon_phonetic.keyboard_info
  release/m/mon_phonetic/mon_phonetic.kpj
  release/m/mon_phonetic/source/help/mon_phonetic.php
  release/m/mon_phonetic/source/help/mon_phonetic.png
  release/m/mon_phonetic/source/help/mon_phonetic_mobile_default.png
  release/m/mon_phonetic/source/help/mon_phonetic_mobile_numeric.png
  release/m/mon_phonetic/source/help/mon_phonetic_mobile_shift.png
  release/m/mon_phonetic/source/help/mon_phonetic_right_alt.png
  release/m/mon_phonetic/source/help/mon_phonetic_s.png
  release/m/mon_phonetic/source/help/mon_phonetic_s_right_alt.png
  release/m/mon_phonetic/source/mon_phonetic.ico
  release/m/mon_phonetic/source/mon_phonetic.keyman-touch-layout
  release/m/mon_phonetic/source/mon_phonetic.kmn
  release/m/mon_phonetic/source/mon_phonetic.kps
  release/m/mon_phonetic/source/mon_phonetic.kvks
  release/m/mon_phonetic/source/readme.htm
  release/m/mon_phonetic/source/welcome/mon_phonetic.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_mobile_default.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_mobile_numeric.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_mobile_shift.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_right_alt.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_s.png
  release/m/mon_phonetic/source/welcome/mon_phonetic_s_right_alt.png
  release/m/mon_phonetic/source/welcome/welcome.htm
Labels: keyboard, new

#1689 [khmer_angkor] update rules and add regression test
  release/k/khmer_angkor/HISTORY.md
  release/k/khmer_angkor/README.md
  release/k/khmer_angkor/extras/regression_tests/Robat.xml
  release/k/khmer_angkor/extras/regression_tests/ស្ប៊ី.xml
  release/k/khmer_angkor/extras/regression_tests/ហ្វ៊ី.xml
  release/k/khmer_angkor/khmer_angkor.kpj
  release/k/khmer_angkor/source/khmer_angkor.kmn
Labels: enhancement, keyboard

#1692 fix(sil_euro_latin): use of KeymanWeb_KeyHoverColor
  release/sil/sil_euro_latin/source/sil_euro_latin_js.txt
Labels: fix

#1693 [font_scheherazade] Update to new version of font
  release/shared/fonts/sil/scheherazade_new/FONTLOG.txt
  release/shared/fonts/sil/scheherazade_new/ScheherazadeNew-Bold.ttf
  release/shared/fonts/sil/scheherazade_new/ScheherazadeNew-Regular.ttf
Labels: enhancement

#1695 [sil_myanmar_my3] Update touch layout
  release/sil/sil_myanmar_my3/HISTORY.md
  release/sil/sil_myanmar_my3/README.md
  release/sil/sil_myanmar_my3/sil_myanmar_my3.kpj
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.keyman-touch-layout
  release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kmn
Labels: enhancement
