Repository keymanapp/keyboards, pull requests merged in 2021-05, with the labels that each got.

#1521 [basic_kbdnko] Update Layouts
  release/basic/basic_kbdnko/HISTORY.md
  release/basic/basic_kbdnko/LICENSE.md
  release/basic/basic_kbdnko/README.md
  release/basic/basic_kbdnko/basic_kbdnko.keyboard_info
  release/basic/basic_kbdnko/basic_kbdnko.kpj
  release/basic/basic_kbdnko/source/basic_kbdnko.keyman-touch-layout
  release/basic/basic_kbdnko/source/basic_kbdnko.kmn
  release/basic/basic_kbdnko/source/basic_kbdnko.kps
  release/basic/basic_kbdnko/source/basic_kbdnko.kvks
  release/basic/basic_kbdnko/source/help/basic_kbdnko.php
  release/basic/basic_kbdnko/source/readme.htm
  release/basic/basic_kbdnko/source/welcome/LayoutU_.png
  release/basic/basic_kbdnko/source/welcome/LayoutU_S.png
  release/basic/basic_kbdnko/source/welcome/tablet_default.png
  release/basic/basic_kbdnko/source/welcome/tablet_shift.png
  release/basic/basic_kbdnko/source/welcome/welcome.htm
Labels: enhancement, keyboard, ready-to-merge

#1538 [malar_malayalam] Update to version 1.4
  release/m/malar_malayalam/HISTORY.md
  release/m/malar_malayalam/LICENSE.md
  release/m/malar_malayalam/README.md
  release/m/malar_malayalam/extras/malar_malayalam.tex
  release/m/malar_malayalam/malar_malayalam.kpj
  release/m/malar_malayalam/source/help/malar_malayalam.jpg
  release/m/malar_malayalam/source/help/malar_malayalam.pdf
  release/m/malar_malayalam/source/malar_malayalam.kmn
  release/m/malar_malayalam/source/malar_malayalam.kps
  release/m/malar_malayalam/source/welcome/malar_malayalam.jpg
  release/m/malar_malayalam/source/welcome/malar_malayalam.pdf
Labels: enhancement, keyboard

#1511 [indonesia] keyboard layout version 2.0
  .gitignore
  release/i/indonesia/HISTORY.md
  release/i/indonesia/LICENSE.md
  release/i/indonesia/README.md
  release/i/indonesia/indonesia.kpj
  release/i/indonesia/source/indonesia.keyman-touch-layout
  release/i/indonesia/source/indonesia.kmn
Labels: enhancement, keyboard

#1548 [fix_php] Improvements to help files
  release/basic/basic_kbdmon/source/help/basic_kbdmon.php
  release/sil/sil_ethiopic/source/help/sil_ethiopic.php
  release/sil/sil_myanmar_mywinext/source/help/sil_myanmar_mywinext.php
Labels: enhancement

#1550 [sil_kmhmu] feat: add special font for the On Screen Keyboard to improve display of diacritics
  release/shared/fonts/kmhmu/Lao OSK.TTF
  release/sil/sil_kmhmu/HISTORY.md
  release/sil/sil_kmhmu/LICENSE.md
  release/sil/sil_kmhmu/sil_kmhmu.kpj
  release/sil/sil_kmhmu/source/help/sil_kmhmu.php
  release/sil/sil_kmhmu/source/sil_kmhmu.kmn
  release/sil/sil_kmhmu/source/sil_kmhmu.kps
  release/sil/sil_kmhmu/source/sil_kmhmu.kvks
  release/sil/sil_kmhmu/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1552 [jawa] Version 2.0 on behalf of author
  release/j/jawa/HISTORY.md
  release/j/jawa/LICENSE.md
  release/j/jawa/README.md
  release/j/jawa/jawa.keyboard_info
  release/j/jawa/jawa.kpj
  release/j/jawa/source/help/jawa.php
  release/j/jawa/source/jawa.keyman-touch-layout
  release/j/jawa/source/jawa.kmn
  release/j/jawa/source/jawa.kps
  release/j/jawa/source/jawa.kvks
  release/j/jawa/source/readme.htm
  release/j/jawa/source/welcome/01.jpg
  release/j/jawa/source/welcome/02.jpg
  release/j/jawa/source/welcome/03.jpg
  release/j/jawa/source/welcome/04.jpg
  release/j/jawa/source/welcome/05.jpg
  release/j/jawa/source/welcome/06.jpg
  release/j/jawa/source/welcome/07.jpg
  release/j/jawa/source/welcome/08.jpg
  release/j/jawa/source/welcome/Layout.xml
  release/j/jawa/source/welcome/LayoutU_.png
  release/j/jawa/source/welcome/LayoutU_A.png
  release/j/jawa/source/welcome/LayoutU_S.png
  release/j/jawa/source/welcome/welcome.htm
  release/j/jawa/source/welcome/welcome2.htm
  release/shared/fonts/javanese/NotoSansJavanese-Regular2.0.ttf
Labels: enhancement, keyboard

#1551 [fix_silEthi_php] Fix help file to look as expected by Keyman
  release/sil/sil_ethiopic/source/help/sil_ethiopic.php
Labels: enhancement

#1554 [hieroglyphic] Update help file
  release/h/hieroglyphic/README.md
  release/h/hieroglyphic/hieroglyphic.keyboard_info
  release/h/hieroglyphic/source/help/hieroglyphic.php
Labels: enhancement

#1553 [sil_ipa] Fix conflict with DE hardware keyboard
  release/sil/sil_ipa/HISTORY.md
  release/sil/sil_ipa/LICENSE.md
  release/sil/sil_ipa/README.md
  release/sil/sil_ipa/sil_ipa.kpj
  release/sil/sil_ipa/source/help/sil_ipa.php
  release/sil/sil_ipa/source/sil_ipa.kmn
  release/sil/sil_ipa/source/sil_ipa.kps
  release/sil/sil_ipa/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1539 [sil_bunong] Bunong (SIL) Keyboard
  release/sil/sil_bunong/HISTORY.md
  release/sil/sil_bunong/LICENSE.md
  release/sil/sil_bunong/README.md
  release/sil/sil_bunong/sil_bunong.keyboard_info
  release/sil/sil_bunong/sil_bunong.kpj
  release/sil/sil_bunong/source/help/phone_longpress.png
  release/sil/sil_bunong/source/help/sil_bunong.php
  release/sil/sil_bunong/source/readme.htm
  release/sil/sil_bunong/source/sil_bunong.css
  release/sil/sil_bunong/source/sil_bunong.ico
  release/sil/sil_bunong/source/sil_bunong.keyman-touch-layout
  release/sil/sil_bunong/source/sil_bunong.kmn
  release/sil/sil_bunong/source/sil_bunong.kps
  release/sil/sil_bunong/source/sil_bunong.kvks
  release/sil/sil_bunong/source/welcome/desktop_layout_default.png
  release/sil/sil_bunong/source/welcome/desktop_layout_shift.png
  release/sil/sil_bunong/source/welcome/phone_layout_default.png
  release/sil/sil_bunong/source/welcome/phone_layout_shift.png
  release/sil/sil_bunong/source/welcome/phone_longpress.png
  release/sil/sil_bunong/source/welcome/tablet_layout_default.png
  release/sil/sil_bunong/source/welcome/tablet_layout_shift.png
  release/sil/sil_bunong/source/welcome/welcome.htm
Labels: keyboard, new, ready-to-merge

#1560 [old_hungarian] New keyboard
  release/o/old_hungarian/HISTORY.md
  release/o/old_hungarian/LICENSE.md
  release/o/old_hungarian/README.md
  release/o/old_hungarian/assets/OldHungarianLICENSE.txt
  release/o/old_hungarian/assets/OldHungarian_Full.ttf
  release/o/old_hungarian/old_hungarian.keyboard_info
  release/o/old_hungarian/old_hungarian.kpj
  release/o/old_hungarian/source/help/old_hungarian.php
  release/o/old_hungarian/source/old_hungarian.keyman-touch-layout
  release/o/old_hungarian/source/old_hungarian.kmn
  release/o/old_hungarian/source/old_hungarian.kps
  release/o/old_hungarian/source/old_hungarian.kvks
  release/o/old_hungarian/source/readme.htm
  release/o/old_hungarian/source/welcome/LayoutU_.png
  release/o/old_hungarian/source/welcome/LayoutU_RA.png
  release/o/old_hungarian/source/welcome/LayoutU_S.png
  release/o/old_hungarian/source/welcome/LayoutU_SRA.png
  release/o/old_hungarian/source/welcome/welcome.htm
Labels: keyboard, new
