Repository keymanapp/keyboards, pull requests merged in 2021-08, with the labels that each got.

#1623 [colchis_phonetic] New keyboard
  experimental/c/colchis_phonetic/HISTORY.md
  experimental/c/colchis_phonetic/LICENSE.md
  experimental/c/colchis_phonetic/README.md
  experimental/c/colchis_phonetic/colchis_phonetic.keyboard_info
  experimental/c/colchis_phonetic/colchis_phonetic.kpj
  experimental/c/colchis_phonetic/source/colchis_phonetic.keyman-touch-layout
  experimental/c/colchis_phonetic/source/colchis_phonetic.kmn
  experimental/c/colchis_phonetic/source/colchis_phonetic.kps
  experimental/c/colchis_phonetic/source/colchis_phonetic.kvks
  experimental/c/colchis_phonetic/source/help/colchis_phonetic.php
  experimental/c/colchis_phonetic/source/readme.htm
  experimental/c/colchis_phonetic/source/welcome/LayoutU_.png
  experimental/c/colchis_phonetic/source/welcome/LayoutU_S.png
  experimental/c/colchis_phonetic/source/welcome/welcome.htm
Labels: keyboard, new

#1625 [nlci_bengali_winscript] new keyboard on behalf of NLCI
  release/nlci/nlci_bengali_winscript/HISTORY.md
  release/nlci/nlci_bengali_winscript/LICENSE.md
  release/nlci/nlci_bengali_winscript/README.md
  release/nlci/nlci_bengali_winscript/nlci_bengali_winscript.keyboard_info
  release/nlci/nlci_bengali_winscript/nlci_bengali_winscript.kpj
  release/nlci/nlci_bengali_winscript/source/help/nlci_bengali_winscript.php
  release/nlci/nlci_bengali_winscript/source/nlci_bengali_winscript.ico
  release/nlci/nlci_bengali_winscript/source/nlci_bengali_winscript.kmn
  release/nlci/nlci_bengali_winscript/source/nlci_bengali_winscript.kps
  release/nlci/nlci_bengali_winscript/source/nlci_bengali_winscript.kvks
  release/nlci/nlci_bengali_winscript/source/readme.htm
  release/nlci/nlci_bengali_winscript/source/welcome/welcome.htm
Labels: keyboard, new

#1609 [fv_taltan] restore touch layout to Tāłtān
  release/fv/fv_taltan/HISTORY.md
  release/fv/fv_taltan/README.md
  release/fv/fv_taltan/fv_taltan.kpj
  release/fv/fv_taltan/source/fv_taltan.kmn
  release/fv/fv_taltan/source/fv_tsilhqotin.keyman-touch-layout
Labels: fix

#1637 [sil_bunong] add translations to welcome page
  release/sil/sil_bunong/HISTORY.md
  release/sil/sil_bunong/README.md
  release/sil/sil_bunong/sil_bunong.kpj
  release/sil/sil_bunong/source/help/sil_bunong.php
  release/sil/sil_bunong/source/sil_bunong.kmn
  release/sil/sil_bunong/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1472 [sil_madi] Latin based keyboard for Madi language
  release/sil/sil_madi/HISTORY.md
  release/sil/sil_madi/LICENSE.md
  release/sil/sil_madi/README.md
  release/sil/sil_madi/sil_madi.keyboard_info
  release/sil/sil_madi/sil_madi.kpj
  release/sil/sil_madi/source/help/phone_longpress.png
  release/sil/sil_madi/source/help/sil_madi.php
  release/sil/sil_madi/source/readme.htm
  release/sil/sil_madi/source/sil_madi.css
  release/sil/sil_madi/source/sil_madi.ico
  release/sil/sil_madi/source/sil_madi.keyman-touch-layout
  release/sil/sil_madi/source/sil_madi.kmn
  release/sil/sil_madi/source/sil_madi.kps
  release/sil/sil_madi/source/sil_madi.kvks
  release/sil/sil_madi/source/welcome/keyboard_layout.png
  release/sil/sil_madi/source/welcome/phone_default.png
  release/sil/sil_madi/source/welcome/phone_longpress.png
  release/sil/sil_madi/source/welcome/phone_numeric.png
  release/sil/sil_madi/source/welcome/phone_shift.png
  release/sil/sil_madi/source/welcome/tablet_default.png
  release/sil/sil_madi/source/welcome/tablet_shift.png
  release/sil/sil_madi/source/welcome/welcome.htm
Labels: keyboard, new

#1605 feat: xmllint .kps files
  build.sh
  release/sil/sil_nubian/source/sil_nubian.kps
  resources/compile.sh
  resources/validate.sh
  tools/kps.xsd
Labels: enhancement

#1642 [colchis_latin] Resize keys for mobile layout
  experimental/c/colchis_latin/HISTORY.md
  experimental/c/colchis_latin/README.md
  experimental/c/colchis_latin/colchis_latin.kpj
  experimental/c/colchis_latin/source/colchis_latin.keyman-touch-layout
  experimental/c/colchis_latin/source/colchis_latin.kmn
Labels: enhancement

#1654 [sil_bunong] fix a long press key output
  release/sil/sil_bunong/HISTORY.md
  release/sil/sil_bunong/README.md
  release/sil/sil_bunong/sil_bunong.kpj
  release/sil/sil_bunong/source/sil_bunong.keyman-touch-layout
  release/sil/sil_bunong/source/sil_bunong.kmn
Labels: bug, enhancement, keyboard, fix
