Repository keymanapp/keyboards, pull requests merged in 2022-08, with the labels that each got.

#1937 [choctaw_modern] New keyboard
  release/c/choctaw_modern/HISTORY.md
  release/c/choctaw_modern/LICENSE.md
  release/c/choctaw_modern/README.md
  release/c/choctaw_modern/choctaw_modern.keyboard_info
  release/c/choctaw_modern/choctaw_modern.kpj
  release/c/choctaw_modern/source/choctaw_modern.keyman-touch-layout
  release/c/choctaw_modern/source/choctaw_modern.kmn
  release/c/choctaw_modern/source/choctaw_modern.kps
  release/c/choctaw_modern/source/choctaw_modern.kvks
  release/c/choctaw_modern/source/help/choctaw_modern.php
  release/c/choctaw_modern/source/readme.htm
  release/c/choctaw_modern/source/welcome/LayoutU_.png
  release/c/choctaw_modern/source/welcome/LayoutU_RA.png
  release/c/choctaw_modern/source/welcome/LayoutU_S.png
  release/c/choctaw_modern/source/welcome/LayoutU_SRA.png
  release/c/choctaw_modern/source/welcome/mobile.png
  release/c/choctaw_modern/source/welcome/mobile_default.png
  release/c/choctaw_modern/source/welcome/mobile_numeric.png
  release/c/choctaw_modern/source/welcome/mobile_shift.png
  release/c/choctaw_modern/source/welcome/welcome.htm
Labels: keyboard, new

#1948 [cabecar] Update online help file
  release/c/cabecar/source/help/cabecar.php
Labels: bug

#1949 [pid_piaroa] add ü̧/Ü̧ to keyboard
  release/p/pid_piaroa/HISTORY.md
  release/p/pid_piaroa/LICENSE.md
  release/p/pid_piaroa/README.md
  release/p/pid_piaroa/pid_piaroa.kpj
  release/p/pid_piaroa/source/help/pid_piaroa.php
  release/p/pid_piaroa/source/pid_piaroa.kmn
  release/p/pid_piaroa/source/pid_piaroa.kps
  release/p/pid_piaroa/source/readme.htm
  release/p/pid_piaroa/source/welcome.htm
Labels: enhancement, keyboard

#1955 [old_hungarian] Changes to support &CasedKeys
  release/o/old_hungarian/HISTORY.md
  release/o/old_hungarian/old_hungarian.keyboard_info
  release/o/old_hungarian/old_hungarian.kpj
  release/o/old_hungarian/source/help/old_hungarian.php
  release/o/old_hungarian/source/old_hungarian.keyman-touch-layout
  release/o/old_hungarian/source/old_hungarian.kmn
  release/o/old_hungarian/source/readme.htm
  release/o/old_hungarian/source/welcome/welcome.htm
Labels: enhancement

#1953 [bj_cree_east / bj_oji_cree] Update keyboards to use NFC
  release/bj/bj_cree_east/HISTORY.md
  release/bj/bj_cree_east/LICENSE.md
  release/bj/bj_cree_east/README.md
  release/bj/bj_cree_east/bj_cree_east.keyboard_info
  release/bj/bj_cree_east/bj_cree_east.kpj
  release/bj/bj_cree_east/source/bj_cree_east.keyman-touch-layout
  release/bj/bj_cree_east/source/bj_cree_east.kmn
  release/bj/bj_cree_east/source/bj_cree_east.kps
  release/bj/bj_cree_east/source/bjcrus.ttf
  release/bj/bj_cree_east/source/help/bj_cree_east.php
  release/bj/bj_cree_east/source/options.htm
  release/bj/bj_cree_east/source/readme.htm
  release/bj/bj_cree_east/source/welcome/welcome.htm
  release/bj/bj_oji_cree/HISTORY.md
  release/bj/bj_oji_cree/LICENSE.md
  release/bj/bj_oji_cree/README.md
  release/bj/bj_oji_cree/bj_oji_cree.keyboard_info
  release/bj/bj_oji_cree/bj_oji_cree.kpj
  release/bj/bj_oji_cree/source/bj_oji_cree.keyman-touch-layout
  release/bj/bj_oji_cree/source/bj_oji_cree.kmn
  release/bj/bj_oji_cree/source/bj_oji_cree.kps
  release/bj/bj_oji_cree/source/bj_oji_cree.kvks
  release/bj/bj_oji_cree/source/bjcrus.ttf
  release/bj/bj_oji_cree/source/bjcrusb.ttf
  release/bj/bj_oji_cree/source/help/bj_oji_cree.php
  release/bj/bj_oji_cree/source/options.htm
  release/bj/bj_oji_cree/source/readme.htm
  release/bj/bj_oji_cree/source/welcome/welcome.htm
  release/shared/fonts/cree/bjcrusb.ttf
Labels: enhancement

#1958 [koreguaje] Add online help
  experimental/k/koreguaje/source/help/koreguaje.php
Labels: enhancement

#1960 [bj_mista_wasaha_cree] Update to use NFC
  release/bj/bj_mista_wasaha_cree/HISTORY.md
  release/bj/bj_mista_wasaha_cree/LICENSE.md
  release/bj/bj_mista_wasaha_cree/README.md
  release/bj/bj_mista_wasaha_cree/bj_mista_wasaha_cree.keyboard_info
  release/bj/bj_mista_wasaha_cree/bj_mista_wasaha_cree.kpj
  release/bj/bj_mista_wasaha_cree/source/bj_mista_wasaha_cree.kmn
  release/bj/bj_mista_wasaha_cree/source/bj_mista_wasaha_cree.kps
  release/bj/bj_mista_wasaha_cree/source/help/bj_mista_wasaha_cree.php
  release/bj/bj_mista_wasaha_cree/source/options.htm
  release/bj/bj_mista_wasaha_cree/source/readme.htm
  release/bj/bj_mista_wasaha_cree/source/welcome/welcome.htm
  release/sil/sil_sgaw_karen/HISTORY.md
  release/sil/sil_sgaw_karen/LICENSE.md
  release/sil/sil_sgaw_karen/README.md
  release/sil/sil_sgaw_karen/sil_sgaw_karen.kpj
  release/sil/sil_sgaw_karen/source/help/mobile_layout_longpress.png
  release/sil/sil_sgaw_karen/source/help/sil_sgaw_karen.php
  release/sil/sil_sgaw_karen/source/readme.htm
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.keyman-touch-layout
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kmn
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kps
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kvks
  release/sil/sil_sgaw_karen/source/welcome/desktop_layout_default.png
  release/sil/sil_sgaw_karen/source/welcome/desktop_layout_shift.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_default.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_longpress.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_numeric.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_shift.png
  release/sil/sil_sgaw_karen/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1956 [sil_sgaw_karen] update four keys
  release/sil/sil_sgaw_karen/HISTORY.md
  release/sil/sil_sgaw_karen/LICENSE.md
  release/sil/sil_sgaw_karen/README.md
  release/sil/sil_sgaw_karen/sil_sgaw_karen.kpj
  release/sil/sil_sgaw_karen/source/help/mobile_layout_longpress.png
  release/sil/sil_sgaw_karen/source/help/sil_sgaw_karen.php
  release/sil/sil_sgaw_karen/source/readme.htm
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.keyman-touch-layout
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kmn
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kps
  release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kvks
  release/sil/sil_sgaw_karen/source/welcome/desktop_layout_default.png
  release/sil/sil_sgaw_karen/source/welcome/desktop_layout_shift.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_default.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_longpress.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_numeric.png
  release/sil/sil_sgaw_karen/source/welcome/mobile_layout_shift.png
  release/sil/sil_sgaw_karen/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1964 fix: Lowercase png and jpg filenames for help
  legacy/a/amazigh_lat.kmn/source/help/amazigh_lat.kmn.php
  legacy/a/amazigh_lat/source/help/amazigh_lat.php
  legacy/e/european/source/help/uppercase.png
  legacy/e/european2/source/help/uppercase.png
  legacy/n/ndailu keyman keyboard/source/help/DaiLue Keyboard Shifted.png
  legacy/n/ndailu keyman keyboard/source/help/DaiLue Keyboard.png
  legacy/s/sabdalipiunicode/source/help/kbdlayout.jpg
  legacy/t/turkmen/source/help/turkmen.php
  release/a/ahom_star/source/help/phone_longpress.png
  release/nlci/nlci_gujarati_winscript/source/help/Gujarati keyboard.png
  release/nlci/nlci_gujarati_winscript/source/welcome/Gujarati keyboard.png
  release/s/soqotri_arabic/source/help/soqotri_arabic.php
  release/s/soqotri_arabic/source/welcome/welcome.htm
  release/sil/sil_tawallammat/source/help/sil_tawallammat.php
  release/u/ukwuani/source/help/ukwuani.php
  release/u/ukwuani/source/welcome/welcome.htm
  release/u/uma_phonetic/source/welcome/welcome.htm
Labels: chore

#1929 correct font name
  release/k/khmer_angkor/khmer_angkor.kpj
  release/k/khmer_angkor/source/khmer_angkor.kps
  release/shared/fonts/khmer/busrakbd/khmer_busra_kbd.ttf
  release/sil/sil_jarai/sil_jarai.kpj
  release/sil/sil_jarai/source/sil_jarai.kps
Labels: fix

#1972 [utf8_kmn] Update source to utf-8
  release/s/syriac_arabic/source/syriac_arabic.kmn
  release/sil/sil_hebr_grek_trans/source/sil_hebr_grek_trans.kmn
  release/sil/sil_pan_africa_mnemonic/source/sil_pan_africa_mnemonic.kmn
  release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kmn
  release/sil/sil_yoruba8/source/sil_yoruba8.kmn
Labels: infrastructure
