Repository keymanapp/keyboards, pull requests merged in 2022-02, with the labels that each got.

#1732 [basic_kbdhebl3] Update OSK and touch
  release/basic/basic_kbdhebl3/HISTORY.md
  release/basic/basic_kbdhebl3/LICENSE.md
  release/basic/basic_kbdhebl3/README.md
  release/basic/basic_kbdhebl3/basic_kbdhebl3.keyboard_info
  release/basic/basic_kbdhebl3/basic_kbdhebl3.kpj
  release/basic/basic_kbdhebl3/source/basic_kbdhebl3.keyman-touch-layout
  release/basic/basic_kbdhebl3/source/basic_kbdhebl3.kmn
  release/basic/basic_kbdhebl3/source/basic_kbdhebl3.kps
  release/basic/basic_kbdhebl3/source/basic_kbdhebl3.kvks
  release/basic/basic_kbdhebl3/source/help/basic_kbdhebl3.php
  release/basic/basic_kbdhebl3/source/readme.htm
  release/basic/basic_kbdhebl3/source/welcome/LayoutU_.png
  release/basic/basic_kbdhebl3/source/welcome/LayoutU_RA.png
  release/basic/basic_kbdhebl3/source/welcome/LayoutU_S.png
  release/basic/basic_kbdhebl3/source/welcome/LayoutU_SRA.png
  release/basic/basic_kbdhebl3/source/welcome/desktop_layout.png
  release/basic/basic_kbdhebl3/source/welcome/touch_layout_default.png
  release/basic/basic_kbdhebl3/source/welcome/touch_layout_longpress.png
  release/basic/basic_kbdhebl3/source/welcome/touch_layout_numeric.png
  release/basic/basic_kbdhebl3/source/welcome/touch_layout_shift.png
  release/basic/basic_kbdhebl3/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1734 [sil_bunong] updates
  release/sil/sil_bunong/HISTORY.md
  release/sil/sil_bunong/LICENSE.md
  release/sil/sil_bunong/README.md
  release/sil/sil_bunong/sil_bunong.keyboard_info
  release/sil/sil_bunong/sil_bunong.kpj
  release/sil/sil_bunong/source/help/sil_bunong.php
  release/sil/sil_bunong/source/readme.htm
  release/sil/sil_bunong/source/sil_bunong.css
  release/sil/sil_bunong/source/sil_bunong.keyman-touch-layout
  release/sil/sil_bunong/source/sil_bunong.kmn
  release/sil/sil_bunong/source/sil_bunong.kps
  release/sil/sil_bunong/source/sil_bunong.kvks
  release/sil/sil_bunong/source/welcome/desktop_layout_default.png
  release/sil/sil_bunong/source/welcome/desktop_layout_shift.png
  release/sil/sil_bunong/source/welcome/tablet_layout_default.png
  release/sil/sil_bunong/source/welcome/tablet_layout_shift.png
  release/sil/sil_bunong/source/welcome/welcome.htm
Labels: enhancement, keyboard, ready-to-merge

#1735 [AndikaAfr-font] Add subset fonts to repo
  release/shared/fonts/sil/andika_subsets/AndikaAPac-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaAfr-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaAm-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaCyr-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaCyrE-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaEur-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaPhon-R.ttf
  release/shared/fonts/sil/andika_subsets/AndikaSubsets_README.txt
  release/shared/fonts/sil/andika_subsets/AndikaViet-R.ttf
  release/shared/fonts/sil/andika_subsets/FONTLOG.txt
  release/shared/fonts/sil/andika_subsets/OFL-FAQ.txt
  release/shared/fonts/sil/andika_subsets/OFL.txt
Labels: infrastructure

#1750 [masaram_gondi] Changes on behalf of author
  release/m/masaram_gondi/HISTORY.md
  release/m/masaram_gondi/README.md
  release/m/masaram_gondi/masaram_gondi.kpj
  release/m/masaram_gondi/source/masaram_gondi.keyman-touch-layout
  release/m/masaram_gondi/source/masaram_gondi.kmn
  release/m/masaram_gondi/source/masaram_gondi.kps
  release/m/masaram_gondi/source/readme.htm
  release/m/masaram_gondi/source/welcome/welcome.htm
Labels: enhancement, keyboard

#1753 [ttw_dan] Update Dan font to new version and bumped kbd version
  release/l/libtralo/HISTORY.md
  release/l/libtralo/LICENSE.md
  release/l/libtralo/README.md
  release/l/libtralo/libtralo.kpj
  release/l/libtralo/source/libtralo.kmn
  release/l/libtralo/source/libtralo.kps
  release/l/libtralo/source/libtralo.kvks
  release/shared/fonts/sil/charis_dan/CharisSIL-Dan-Bold.ttf
  release/shared/fonts/sil/charis_dan/CharisSIL-Dan-BoldItalic.ttf
  release/shared/fonts/sil/charis_dan/CharisSIL-Dan-Italic.ttf
  release/shared/fonts/sil/charis_dan/CharisSIL-Dan-Regular.ttf
  release/shared/fonts/sil/charis_dan/CharisSILDan_FONTLOG.txt
  release/shared/fonts/sil/charis_dan/CharisSILDan_README.txt
  release/shared/fonts/sil/charis_dan/OFL-FAQ.txt
  release/shared/fonts/sil/charis_dan/OFL.txt
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan-Bold.ttf
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan-BoldItalic.ttf
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan-Italic.ttf
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan-Regular.ttf
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan_FONTLOG.txt
  release/shared/fonts/sil/charis_sil_dan/CharisSILDan_README.txt
Labels: enhancement, keyboard

#1761 [sil_devanagari_romanized] Update online help file only
  release/sil/sil_devanagari_romanized/source/help/sil_devanagari_romanized.php
Labels: infrastructure
