Repository keymanapp/keyboards, pull requests merged in 2022-06, with the labels that each got.

#1879 [hausa_ajami_qwerty] Update keyboard to fix two issues
  release/h/hausa_ajami_qwerty/HISTORY.md
  release/h/hausa_ajami_qwerty/source/hausa_ajami_qwerty.kmn
  release/h/hausa_ajami_qwerty/source/hausa_ajami_qwerty.kps
Labels: enhancement

#1874 [easy_chakma] Update font and icon
  release/e/easy_chakma/HISTORY.md
  release/e/easy_chakma/LICENSE.md
  release/e/easy_chakma/README.md
  release/e/easy_chakma/easy_chakma.kpj
  release/e/easy_chakma/source/easy_chakma.ico
  release/e/easy_chakma/source/easy_chakma.kmn
  release/e/easy_chakma/source/easy_chakma.kps
  release/e/easy_chakma/source/readme.htm
  release/e/easy_chakma/source/welcome.htm
  release/shared/fonts/chakma/RibengUni-Regular.ttf
Labels: enhancement, keyboard

#1873 [colchis_latin] Revised mobile layouts per user request
  release/c/colchis_latin/HISTORY.md
  release/c/colchis_latin/colchis_latin.kpj
  release/c/colchis_latin/source/colchis_latin.keyman-touch-layout
  release/c/colchis_latin/source/colchis_latin.kmn
  release/c/colchis_latin/source/help/colchis_latin.php
Labels: enhancement

#1852 [mon_anonta] Fix duplicate stores (addK, ldiaK, ldiaU)
  release/m/mon_anonta/HISTORY.md
  release/m/mon_anonta/LICENSE.md
  release/m/mon_anonta/README.md
  release/m/mon_anonta/mon_anonta.kpj
  release/m/mon_anonta/source/mon_anonta.kmn
  release/m/mon_anonta/source/mon_anonta.kps
Labels: work-in-progress
